### ISSUE TITLE
Feature request moose.Function should be able to accept variables names which are just not x0, x1, .. y0, y1

### ISSUE THREAD

**Issue by subhacom** [BhallaLab/moose#161]
Currently `moose.Function` variables must be named as x0, x1, ...., or y0, y1, etc.. I suggest that in addition to this, `moose.Function` should also accept any keyword prefixed with `var_` or `v_` (or something similar) as variables. This will make expressions more readable e.g. var_CAMKII over x0 representing CAMKII etc.

Reported by: dilawar

**Comment by dilawar** [comment]
An attempt is being made on https://github.com/BhallaLab/moose-core/pull/367

**Comment by dilawar** [comment]
This is implemented in https://github.com/BhallaLab/moose-core/pull/390 . This is done at the Python level. In nutshell, a user is allowed to have an expression with arbitrarily named variables e.g. `Ca+sin(Mg)` instead of `x0+sin(x1)`. `Ca` and `Mg` will be replaced by `x0` and `x1` whenever user connects these pool to the function. This is possible because the new parser based on exprtk (https://github.com/BhallaLab/moose-core/pull/387) allows dynamic lookup at runtime. More details are/will be at the PR.

**Comment by dilawar** [comment]
All tests are passing in https://github.com/BhallaLab/moose-core/pull/390 . When the PR is merged, this should be closed.
