### ISSUE TITLE
On 15.10 moosegui doesn't open missing mtypes.py but the file exists in github

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose#193]
This is tested on a naive Ubuntu 15.10 system, install from source https://software.opensuse.org/download.html, moosegui doesn't open as it is saying missing mtypes.py file but the file exists in github.com/BhallaLab/moose-gui/
May be its the same with other version also, check.

**Comment by dilawar** [comment]
Yes. This file is not in content of package. Is it a recent addition?

**Comment by dilawar** [comment]
Seems like a old file. Its is missing from all debian packages -- regardless of
ubuntu version.

**Comment by dilawar** [comment]
Seems like this file is moved to moose-gui very recently (march 2, https://github.com/BhallaLab/moose-gui/commits/2159db08a0dc71d7da063e0f10b037bde6a59e45/mtypes.py ). 

If this repo is stable, I can merge today's commit to packages?

**Comment by hrani** [comment]
The file exists in moose-core/python/moose folder and moosegui was
accessing this file from this path.

And Yes this file is moved from moose-core/python/moose to moose-gui and I
have made necessary changes in the moose-gui folder but looks like while
doing package it has only taken moose-core and deleted the mtypes.py file
but it has not taken from moose-gui folder  the relevant changes made to
file and either added this file.

And I know its missing from all debian packages, but mentioned Ubunut15.10
b'cos I have tested it on.

"If this repo is stable, I can merge today's commit to packages? "

Of course this is stable and working its just moved from moose-core to
moose-gui

**Comment by dilawar** [comment]
Packaging is not done directly from the development repositories. There are
mirrors of these repositories to which a snapshot of repos are merged to. Then
only packaging is done after adding changelog. So I need to know the
version/commit/tag you want to put into package. Ideally you should tag your
repository. See BhallaLab/moose-gui#11.

I've integrated today's moose-gui to packaging repo. If there is a changelog
which users might like to know, you can submit it here. Otherwise I'd add 'files
rearranged' to changelog. 

I hope nothing is changed to `import moose' functionality after moving this
file.

Build log https://build.opensuse.org/build/home:moose/xUbuntu_15.10/x86_64/moose/_log

Failed

Closing the ticket here. As soon as I fixed the build, file should be available
in package. You can reopen it again if this does not fix it.

**Comment by dilawar** [comment]
Revision 22 on OBS (https://build.opensuse.org/package/rdiff/home:moose/moose?linkrev=base&rev=22) fixes it. PyQt5 (which may be default for matplotlib on some system) may not work BhallaLab/moose-gui#13

**Comment by dilawar** [comment]
Tested on 15.10- VirtualBox. Reopen it if problem remains.
