### ISSUE TITLE
moose complied with python3 doesn't import moose

### ISSUE THREAD

**Issue by hrani** [BhallaLab/moose#224]
After compiling moose with python3 using cmake, make, sudo make install, 
moose doesn't import
that is b'cos python site path takes the /usr/local/lib/python3.5/dist-packages (which may be the latest python in the machine)
what is set using cmake is usr/local/lib/python3/dist-packages

**Comment by dilawar** [comment]
Related to BhallaLab/moose-core#230 . Since this repository is right place to fix the import issue, closing the other ticket as duplicate.

**Comment by dilawar** [comment]
Asked a question on stackoverflow to find a good solution to this problem:

https://stackoverflow.com/questions/47322846/python-m-site-user-site-output-is-same-with-or-without-sudo

**Comment by dilawar** [comment]
Above solution breaks the build of moose because `--prefix` is being overwritten by `moose-core` now.

It must be honored by moose-core. During packaging, `--prefix` is non-standard path; after installing into non-standard path, packaging script move the built module in appropriate place. 

Following solution may fix it:

- Given the prefix, construct the `libpath` in the setup.py .
- Revert back the changes and report upstream python3 development about non-standard `setup.py` behaviour. It does not happen on opensuse/fedora/arch-linux. It happens on Ubuntu; and probably MacOSX.

**Comment by dilawar** [comment]
I believe that has been fixed by a PR on moose-core. If not, please reopen it.
